// in src we write all the react code
//scripts/app.js will be our autogenerated file
console.log("Is running");

// JSX - Javascript XML
var template = <h1>Indecision App</h1>;

var appRoot = document.getElementById("app");

// .render(jsx, dom)
ReactDOM.render(template, appRoot);